name = "AssetRegistry"
uuid = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
repo = "https://github.com/JuliaGizmos/AssetRegistry.jl.git"
version = "0.1.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pidfile = "fa939f87-e72e-5be4-a000-7fc836dbe307"

[compat]
JSON = "0.21"
Pidfile = "1.3"
julia = "1"
